swagger: "2.0"
info:
  description: Manage member and rewards
  version: "1.0.0"
  title: "Member Reward API"
host: "localhost:80"
basePath: "/api/v1"
tags:
- name: "memberReward"
  description: |
    Manage Members and Rewards
schemes:
- "http"
paths:
